version: '2'
services:
  servicegui:
    container_name: servicegui
    image: josephkphan/smartmirror-servicegui
    logging:
      driver: "json-file"
      options:
        max-size: 50m
    ports:
      - "5000:5000"
    volumes:
      - ~/Desktop/SchoolWork/SmartMirror/project/data:/usr/src/app/data
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      # NOTE: Change the IP Below to the ip you added via xhost
      # Run Command: 
      # open -a XQuartz 
      # ip=$(ifconfig en0 | grep inet | awk '$1=="inet" {print $2}') && xhost + $ip
      # xhost +local:docker
      - DISPLAY=172.21.119.109:0
  serviceweb:
    container_name: serviceweb
    image: josephkphan/smartmirror-serviceweb
    # restart: always
    logging:
      driver: "json-file"
      options:
        max-size: 50m
    ports:
      - "5001:5001"
    volumes:
      - /Users/josephphan/Desktop/SchoolWork/SmartMirror/project/data:/usr/src/app/data