version: '2'
services:
  servicegui:
    container_name: servicegui
    image: josephkphan/smartmirror/servicegui
    # restart: always
    logging:
      driver: "json-file"
      options:
        max-size: 50m
    ports:
      - "5000:5000"
    volumes:
      - ~/Desktop/SchoolWork/SmartMirror/project/data:/usr/src/app/data
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      #- DISPLAY=unix:0
      - DISPLAY=172.16.0.21:0
  serviceweb:
    container_name: serviceweb
    image: josephkphan/smartmirror/serviceweb
    # restart: always
    logging:
      driver: "json-file"
      options:
        max-size: 50m
    ports:
      - "5001:5001"
    volumes:
      - /Users/josephphan/Desktop/SchoolWork/SmartMirror/project/data:/usr/src/app/data